- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: entrypoint.ps1
    arguments: > # Use this to avoid newline characters in multiline string
      -input1 "Hello"
      -input2 "World"
  displayName: 'Print Hello World'