name: 'Sonarqube Job Trigger'
description: 'Trigger a Sonarqube job'
branding:
  icon: 'terminal'
  color: 'green' 
inputs:
  url:
    description: 'Jenkins full URL including http/https protocol'
    required: false
runs:
  main: 'entrypoint.ps1'
